sudo: true
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose up -d mongo
  - docker-compose up -d slack
  - docker-compose up -d discord
  - sleep 15
  - docker-compose up -d nlp
script:
  - make test
after_failure:
  - sleep 10
  - docker-compose ps
  - docker-compose logs
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
  region: "eu-west-3"
  app: "gary"
  env: "gary-env"
  bucket_name: "elasticbeanstalk-eu-west-3-158084809355"
  on:
    branch: master
