sudo: true
language: python
notifications:
  slack: brainstorm-etna:hMgNrjhxmXb6CpKKRe5e6oTZ
services:
  - docker
before_install:
  - make build
script:
  - make test
after_failure:
  - sleep 10
  - docker-compose ps
  - docker-compose logs
after_success:
  - make stop
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
  region: "eu-west-3"
  app: "gary"
  env: "gary-env"
  bucket_name: "elasticbeanstalk-eu-west-3-158084809355"
  on:
    branch: master
