language: python
sudo: false
notifications:
  slack: brainstorm-etna:hMgNrjhxmXb6CpKKRe5e6oTZ
services:
  - docker
before_install:
  - docker-compose up -d --build
  - docker-compose ps
  - docker exec gary_nlp_1 python training.py
script:
  - make test
after_deploy:
  - echo "done deploying"
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: "$AWS_ACCESS_KEY"
  region: "eu-west-3"
  app: "gary"
  env: "gary-env"
  bucket_name: "elasticbeanstalk-eu-west-3-158084809355"
  on:
    branch: master
