notifications:
  slack: brainstorm-etna:hMgNrjhxmXb6CpKKRe5e6oTZ
sudo: required
language: python
services:
  - docker
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
script:
  - make travis
  - sh -c 'docker exec -it gary_nlp py.test -svv test_chatbot.py'
after_success:
  - make stop
