version: '2'
services:
#  api:
#    hostname: api
#    build:
#      context: gary-api/
#      dockerfile: docker/Dockerfile
#    ports:
#      - 8081:8080
#    volumes:
#      - ./gary-api:/usr/src/app
#      - ./logs/api:/var/log/api
#    environment:
#      - APP=server.js
#      - NODE_ENV=development
#    links:
#      - mongo

  connector-slack:
    hostname: connector-slack
    build:
      context: gary-connector/slack/
      dockerfile: Dockerfile
    volumes:
      - ./gary-connector/slack/:/bot/
      - ./logs/connector/slack/:/var/log/connector/
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - BOT_ID=${BOT_ID}
    links:
      - nlp
    tty: true

  nlp:
    container_name: gary_nlp
    hostname: nlp
    build:
      context: gary-nlp/
      dockerfile: docker/Dockerfile
    volumes:
      - ./gary-nlp:/bot/
      - ./logs/nlp:/var/log/nlp/
    ports:
      - 5051:5000
    links:
      - mongo
    tty: true

  mongo:
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    tty: true
