version: '2'
services:
  mongo:
    container_name: gary_mongo
    hostname: mongo
    image: mongo
    restart: always
    tty: true
  nlp:
    container_name: gary_nlp
    hostname: nlp
    build:
      context: nlp/
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ./nlp:/bot/
      - ./logs/nlp:/var/log/
    ports:
      - 5051:5000
    links:
      - mongo
    tty: true
  connector-slack:
    container_name: gary_slack
    build:
      context: connector/slack/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./connector/slack/:/bot/
      - ./logs/connector/slack/:/var/log/
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_BOT_ID=${SLACK_BOT_ID}
    links:
      - nlp
    tty: true
  connector-discord:
    container_name: gary_discord
    build:
      context: connector/discord/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./connector/discord/:/bot/
      - ./logs/connector/discord/:/var/log/
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    links:
      - nlp
    tty: true
