mongo:
  environment:
    Container: mongo
  image: mongo
nlp:
  command: >
    bash -c "/usr/bin/python2.7 /bot/fixture.py && /usr/bin/python2.7 /bot/training.py && /usr/bin/python2.7 /bot/api.py"
  environment:
    Container: nlp
  image: victorbalssa/nlp-container:v1.0.0
  links:
  - mongo:mongo
  ports:
  - 5051:5000
  volumes:
  - ./nlp:/bot
connectordiscord:
  command:
  - python
  - ./discord_bot_connector.py
  environment:
    Container: discord-co
    DISCORD_TOKEN: ${DISCORD_TOKEN}
  image: victorbalssa/python-container:v1.0.1
  links:
  - nlp:nlp
  volumes:
  - ./connector/discord/:/bot
connectorslack:
  command:
  - python
  - ./slack_bot_connector.py
  environment:
    Container: slack-co
    SLACK_BOT_ID: ${SLACK_BOT_ID}
    SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  image: victorbalssa/python-container:v1.0.1
  links:
  - nlp:nlp
  volumes:
  - ./connector/slack/:/bot
