version: '2'
services:
  connector-slack:
    build:
      context: gary-connector/slack/
      dockerfile: Dockerfile
    volumes:
      - ./gary-connector/slack/:/bot/
      - ./logs/connector/slack/:/var/log/connector/
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - BOT_ID=${BOT_ID}
    links:
      - nlp
    tty: true

  nlp:
    container_name: gary_nlp
    hostname: nlp
    build:
      context: gary-nlp/
      dockerfile: docker/Dockerfile
    volumes:
      - ./gary-nlp:/bot/
      - ./logs/nlp:/var/log/nlp/
    ports:
      - 5051:5000
    links:
      - mongo
    tty: true

  mongo:
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    tty: true
